# Build Script for Apache Ultimate Bad Bot Blocker using GHA
name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: '0 10 * * *'
      - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Software
        run: |
          sudo apt -y install dos2unix
          echo "Install Apache 2.2"
          sudo apt-get install build-essential
          wget http://www-eu.apache.org/dist/httpd/httpd-2.2.32.tar.gz
          tar -xvf httpd-2.2.32.tar.gz
          cd httpd-2.2.32/
          ./configure --prefix=/usr/local/apache2 --enable-mods-shared=all --enable-deflate --enable-proxy --enable-proxy-balancer --enable-proxy-http
          make
          sudo make install
          apache2 -v

