# Build Script for Apache Ultimate Bad Bot Blocker using GHA
name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: '0 10 * * *'
      - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Software
        run: |
          sudo apt -y install dos2unix
          sudo apt-cache showpkg apache2

